Add section to reference shared config in YAML
codefresh-io/docs.codefresh.io pull request #715
Opened 2023-06-05 12:02 UTC by NimRegev

Added section to reference shared config and made content edits

2023-06-07 07:36 UTC, daniel-codefresh requested changes

2023-06-07 07:36 UTC, daniel-codefresh commented on _docs/pipelines/configuration/shared-configuration.md
> +Instead of manually importing the shared configuration contexts with the variables to use into the pipeline, you can reference the shared configuration to use in the pipeline's YAML.
"Instead of manually importing..." - maybe it would be better to emphasize that we we're talking about the UI here.

"you can reference the shared configuration to use in the pipeline's YAML" - IMO it is really important to emphasize the fact that it would only work with a "full YAML" version (not sure about the naming). Today we basically have 2 versions of pipeline YAMLs, the shorter version that we allow users to pass in the Inline YAML screen we have in the pipeline view in the UI, and the longer (full) version that can be created added through the CLI. The shorter version basically supports just a subset of the fields that the longer one supports. Fields like `kind`, `metadata`, `spec` and also the `contexts` field in your example, are only supported in the full spec YAML version. I might be wrong but I think that ATM there is no clear separation of these 2 YAML versions in our docs and it might confuse the readers and make them think that they can use fields like `spec.contexts` in the Inline YAML screen for instance, which will result in an error.

2023-06-12 08:27 UTC, NimRegev commented on _docs/pipelines/configuration/shared-configuration.md
> +If you have a shared configuration named `test-hello` that includes the variable `test=hello`, you can add `spec.contexts.test-hello` to the pipeline YAML, and then reference this variable in the pip
it's correct

2023-06-12 13:23 UTC, daniel-codefresh requested changes

2023-06-12 13:23 UTC, daniel-codefresh commented on _docs/pipelines/configuration/shared-configuration.md
> +For example, you can reference one or more shared configuration contexts directly in the YAML using `spec.contexts` as described below.
not sure i understand - how is this section relevant here? it begins with the words "For example" and describes how you can reference a shared configuration, when the paragraph before talks about create/update/delete operations on shared configurations which is a totally different thing.. Or am I missing something?

2023-06-12 13:26 UTC, NimRegev commented on _docs/pipelines/configuration/shared-configuration.md
> +For example, you can reference one or more shared configuration contexts directly in the YAML using `spec.contexts` as described below.
Good point; i will update as needed

2023-06-13 09:04 UTC, merged