Remove how to KB articles
codefresh-io/docs.codefresh.io pull request #924
Opened 2024-02-12 06:34 UTC by NimRegev

Removed unused invalid How to KB articles after porting content to core doc as relevant

2024-02-12 17:45 UTC, hauskaffee requested changes

2024-02-12 17:45 UTC, hauskaffee commented on _docs/administration/account-user-management/create-codefresh-account.md
Can we add that only Account Owners can delete the account.

2024-02-12 17:46 UTC, hauskaffee commented
The file `out-of-disk-space.md` might be good to keep unless that information is elsewhere.

2024-02-13 06:00 UTC, NimRegev commented on _docs/administration/account-user-management/create-codefresh-account.md
Done

2024-02-13 06:04 UTC, NimRegev commented
> The file `out-of-disk-space.md` might be good to keep unless that information is elsewhere.

Please confirm that it's covered here: https://codefresh.io/docs/docs/pipelines/pipelines/#set-minimum-disk-space-for-a-pipeline-build

2024-02-14 14:25 UTC, hauskaffee commented
@NimRegev Thank you. Forgot about that page and the Ui will contain the information needed.   Thank you.

2024-02-14 14:25 UTC, hauskaffee approved these changes

2024-02-25 12:32 UTC, merged